In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys
from collections import defaultdict
import os
import json
import re
from nltk.corpus import stopwords

from nltk.stem import PorterStemmer,WordNetLemmatizer
Stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [72]:
file_location = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/pos/16_7.txt"
file = open(file_location,'r')
Stopwords = set(stopwords.words('english'))
s = file.read()

s = re.sub('<.*?>',repl = " ", string = s)
s = re.sub(r"[^\w\s']", '', s)
# s = re.sub(r"[/:,-]", ' ', s)

s = s.lower()
# print(s.split())
s= s.split()
final = []
counter = defaultdict(int)
Stemmer = PorterStemmer()
for word in s:
    stemmed_word = Stemmer.stem(word)
    if word not in Stopwords:
        counter[stemmed_word]+=1
print(counter)

defaultdict(<class 'int'>, {'found': 1, 'soso': 1, 'romancedrama': 1, 'nice': 3, 'end': 1, 'gener': 1, 'feel': 1, 'hallmark': 1, 'hall': 1, 'fametyp': 1, 'famili': 1, 'film': 3, 'sleepingbeforemarriag': 1, 'consid': 2, 'normal': 1, 'behavior': 1, 'star': 1, 'jane': 1, 'fonda': 1, 'robert': 1, 'de': 1, 'niro': 1, 'would': 2, 'expect': 1, 'lot': 1, 'rougher': 1, 'movi': 2, 'least': 1, 'languagewis': 1, 'memor': 2, 'part': 1, 'portray': 1, 'difficult': 1, 'must': 1, 'learn': 1, 'read': 1, 'write': 1, 'alreadi': 1, 'adult': 1, "that'": 1, 'big': 1, 'theme': 1, 'involv': 1, 'touch': 1, 'scene': 1, 'honest': 1, 'still': 1, 'fairli': 1, 'mild': 1, 'tale': 1, 'happi': 1, 'recommend': 1})


In [54]:
StemMap = defaultdict()
def Stem(word):
    if word in StemMap:
        return StemMap[word]
    StemMap[word] = Stemmer.stem(word)
    return StemMap[word]

In [55]:
def default_split(directory, vocab = defaultdict(int)):
    
    x = []
    vocab_enum = len(vocab)
    file_names = os.listdir(directory)
    for file_name in file_names:
        file = open(directory+file_name,'r')
        s = file.read()
        s = re.sub('<.*?>',repl = " ", string = s)
        s = re.sub(r"[^\w\s']", '', s)
#         s = re.sub(r"[/:,-]", ' ', s)
        s = s.lower()
        s = s.split()
        counter = defaultdict(int)
        for word in s:
            counter[word]+=1
            if word not in vocab:
                vocab[word] = vocab_enum
                vocab_enum += 1
#         print(np.array(counter))
        x.append(counter)
    return x

In [73]:
def stem_split(directory, stemmed_vocab = defaultdict(int)):
    
    x = []
    vocab_enum = len(stemmed_vocab)
    Stemmer = PorterStemmer()
    file_names = os.listdir(directory)
    Stopwords = set(stopwords.words('english'))
    for file_name in file_names:
        file = open(directory+file_name,'r')
        s = file.read()
        s = re.sub('<.*?>',repl = " ", string = s)
        s = re.sub(r"[^\w\s']", '', s)
#         s = re.sub(r"[/:,-]", ' ', s)
        s = s.lower()
        s = s.split()
        counter = defaultdict(int)
        for word in s:
            stemmed_word = Stem(word)
            if word not in Stopwords:
                counter[stemmed_word]+=1
                if stemmed_word not in stemmed_vocab:
                    stemmed_vocab[stemmed_word] = vocab_enum
                    vocab_enum += 1
#         print(np.array(counter))
        x.append(counter)
    return x

In [74]:
def bigram_split(directory, bigram_vocab = defaultdict(int)):
    x = []
    vocab_enum = len(bigram_vocab)
    Stemmer = PorterStemmer()
    file_names = os.listdir(directory)
    Stopwords = set(stopwords.words('english'))
    for file_name in file_names:
        file = open(directory+file_name,'r')
        s = file.read()
        s = re.sub('<.*?>',repl = " ", string = s)
        s = re.sub(r"[^\w\s']", '', s)
#         s = re.sub(r"[/:,-]", ' ', s)
        s = s.lower()
        s = s.split()
        counter = defaultdict(int)
        wordlist = []
        for word in s:
            stemmed_word = Stem(word)#Stemmer.stem(word)
            if word not in Stopwords:
                wordlist.append(stemmed_word)
            
        
        for i in range(len(wordlist)-1):
            word = wordlist[i]+" "+wordlist[i+1]
            
            counter[word]+=1
            if word not in bigram_vocab:
                    bigram_vocab[word] = vocab_enum
                    vocab_enum += 1
#         print(np.array(counter))
        x.append(counter)
    return x

In [75]:
def trigram_split(directory, trigram_vocab = defaultdict(int)):
    x = []
    vocab_enum = len(trigram_vocab)
    Stemmer = PorterStemmer()
    file_names = os.listdir(directory)
    Stopwords = set(stopwords.words('english'))
    for file_name in file_names:
        file = open(directory+file_name,'r')
        s = file.read()
        s = re.sub('<.*?>',repl = " ", string = s)
        s = re.sub(r"[^\w\s']", '', s)
#         s = re.sub(r"[/:,-]", ' ', s)
        s = s.lower()
        s = s.split()
        counter = defaultdict(int)
        wordlist = []
        for word in s:
            stemmed_word = Stem(word)#Stemmer.stem(word)
            if word not in Stopwords:
                wordlist.append(stemmed_word)
            
        
        for i in range(len(wordlist)-2):
            word = wordlist[i]+" "+wordlist[i+1] + " " + wordlist[i+2]
            
            counter[word]+=1
            if word not in trigram_vocab:
                    trigram_vocab[word] = vocab_enum
                    vocab_enum += 1
#         print(np.array(counter))
        x.append(counter)
    return x

In [289]:
pos_x = stem_split("D:/GitHub/COL774/Assignment 2/data/part1_data/test/pos/")
print(pos_x[0])

defaultdict(<class 'int'>, {'went': 1, 'saw': 2, 'thi': 3, 'movi': 4, 'last': 1, 'night': 1, 'coax': 1, 'friend': 1, 'mine': 1, 'ill': 1, 'admit': 1, 'wa': 6, 'reluct': 1, 'see': 3, 'becaus': 1, 'knew': 1, 'ashton': 1, 'kutcher': 2, 'onli': 2, 'abl': 1, 'comedi': 1, 'wrong': 1, 'play': 2, 'charact': 1, 'jake': 1, 'fischer': 1, 'veri': 1, 'well': 2, 'kevin': 1, 'costner': 1, 'ben': 1, 'randal': 1, 'profession': 1, 'sign': 1, 'good': 1, 'toy': 1, 'emot': 1, 'one': 1, 'exactli': 1, 'entir': 1, 'theater': 2, 'sold': 1, 'overcom': 1, 'laughter': 1, 'dure': 2, 'first': 1, 'half': 2, 'move': 1, 'tear': 2, 'second': 1, 'exit': 1, 'mani': 2, 'women': 1, 'full': 1, 'grown': 1, 'men': 1, 'tri': 1, 'desper': 1, 'let': 1, 'anyon': 1, 'cri': 1, 'great': 1, 'suggest': 1, 'go': 1, 'befor': 1, 'judg': 1})


In [59]:
def train_naive_bayes(x,vocab):
    phi = np.ones(len(vocab))
    n = len(vocab)
    
    for review in x:
        n+=len(review)
        for word in review.keys():
            phi[vocab[word]] += review[word]  
    
    phi/=n
    return phi
    


In [82]:
vocab = defaultdict(int)
file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/pos/"
pos_x = default_split(file_location_pos,vocab)
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/neg/"
neg_x = default_split(file_location_neg,vocab)

phi_pos = train_naive_bayes(pos_x,vocab)
phi_neg = train_naive_bayes(neg_x,vocab)
phi = [phi_neg,phi_pos]
print(len(vocab))

120179


In [314]:
mylist = []
for word in vocab:
    mylist.append(vocab[word])
print(mylist)
print(len(mylist))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [61]:
phi_y = len(os.listdir(file_location_pos))/(len(os.listdir(file_location_pos))+len(os.listdir(file_location_neg)))
print(np.log(phi_y))

-0.6931471805599453


In [62]:
def judge(review,phi,phi_y,vocab):
    prob_1 = np.log(phi_y)
    prob_0 = np.log(1-phi_y)
    for word in review:
        if word not in vocab:
            continue
        prob_0 += review[word] * np.log(phi[0][vocab[word]])
        prob_1 += review[word] * np.log(phi[1][vocab[word]])
    if prob_1 >= prob_0 :
        return 1
    
    return 0

In [63]:
def confusion_matrix(y_pred,y_act) :
    cmat = np.zeros((2,2))
    
    cmat[0,0] = len(np.where((y_pred==y_act) & (y_pred == 1))[0])
    cmat[1,1] = len(np.where((y_pred==y_act) & (y_pred == 0))[0])
    cmat[0,1] = len(np.where((y_pred!=y_act) & (y_pred == 1))[0])
    cmat[1,0] = len(np.where((y_pred!=y_act) & (y_pred == 0))[0])
    
    return cmat

In [83]:
# Training Accuracy

file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/pos/"
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/neg/"
y_act = np.zeros(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos)))
y_act[0:len(os.listdir(file_location_pos))] = 1
y_pred = np.zeros_like(y_act)

iter = 0

pos_x = default_split(file_location_pos)
for review in pos_x:
    y_pred[iter] = judge(review,phi,phi_y,vocab)
    iter += 1

neg_x = default_split(file_location_neg)
for review in neg_x:
    y_pred[iter] = judge(review,phi,phi_y,vocab)
    iter += 1
cmat_train = confusion_matrix(y_pred,y_act)
print(cmat_train)
print(f"Accuracy : {(cmat_train[0,0]+cmat_train[1,1])/np.sum(cmat_train)}")

# Test Accuracy

file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/test/pos/"
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/test/neg/"
y_act = np.zeros(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos)))
y_act[0:len(os.listdir(file_location_pos))] = 1
y_pred = np.zeros_like(y_act)

iter = 0

pos_x = default_split(file_location_pos)
for review in pos_x:
    y_pred[iter] = judge(review,phi,phi_y,vocab)
    iter += 1

neg_x = default_split(file_location_neg)
for review in neg_x:
    y_pred[iter] = judge(review,phi,phi_y,vocab)
    iter += 1
cmat_test = confusion_matrix(y_pred,y_act)
print(cmat_test)
print(f"Accuracy : {(cmat_test[0,0]+cmat_test[1,1])/np.sum(cmat_test)}")

[[11466.  1062.]
 [ 1034. 11438.]]
Accuracy : 0.91616
[[8260.  822.]
 [1740. 4178.]]
Accuracy : 0.8292


In [11]:
# Random Guessing
import random
y_act = np.zeros(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos)))
y_act[0:len(os.listdir(file_location_pos))] = 1
y_pred = np.zeros_like(y_act)

for iter in range(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos))):
    y_pred[iter] = random.randint(0,1)
cmat_random = confusion_matrix(y_pred,y_act)
print(cmat_random)
print(f"Accuracy : {(cmat_random[0,0]+cmat_random[1,1])/np.sum(cmat_random)}")

# All positive
print(len(os.listdir(file_location_pos))/(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos))))    
y_act = np.zeros(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos)))
y_act[0:len(os.listdir(file_location_pos))] = 1
y_pred = np.ones_like(y_act)
cmat_positive = confusion_matrix(y_pred,y_act)
print(cmat_positive)
print(f"Accuracy : {(cmat_positive[0,0]+cmat_positive[1,1])/np.sum(cmat_positive)}")



[[4992. 2582.]
 [5008. 2418.]]
Accuracy : 0.494
0.6666666666666666
[[10000.  5000.]
 [    0.     0.]]
Accuracy : 0.6666666666666666


## Stemming

In [80]:
stemmed_vocab = defaultdict(int)
file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/pos/"
pos_x = stem_split(file_location_pos,stemmed_vocab)
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/neg/"
neg_x = stem_split(file_location_neg,stemmed_vocab)

phi_pos = train_naive_bayes(pos_x,stemmed_vocab)
phi_neg = train_naive_bayes(neg_x,stemmed_vocab)
phi = [phi_neg,phi_pos]

In [66]:
print(stemmed_vocab)

defaultdict(<class 'int'>, {'bromwel': 0, 'high': 1, 'cartoon': 2, 'comedi': 3, 'ran': 4, 'time': 5, 'program': 6, 'school': 7, 'life': 8, 'teacher': 9, '35': 10, 'year': 11, 'teach': 12, 'profess': 13, 'lead': 14, 'believ': 15, 'satir': 16, 'much': 17, 'closer': 18, 'realiti': 19, 'scrambl': 20, 'surviv': 21, 'financi': 22, 'insight': 23, 'student': 24, 'see': 25, 'right': 26, 'pathet': 27, 'pomp': 28, 'petti': 29, 'whole': 30, 'situat': 31, 'remind': 32, 'knew': 33, 'saw': 34, 'episod': 35, 'repeatedli': 36, 'tri': 37, 'burn': 38, 'immedi': 39, 'recal': 40, 'classic': 41, 'line': 42, 'inspector': 43, 'im': 44, 'sack': 45, 'one': 46, 'welcom': 47, 'expect': 48, 'mani': 49, 'adult': 50, 'age': 51, 'think': 52, 'far': 53, 'fetch': 54, 'piti': 55, 'isnt': 56, 'homeless': 57, 'houseless': 58, 'georg': 59, 'carlin': 60, 'state': 61, 'issu': 62, 'never': 63, 'plan': 64, 'help': 65, 'street': 66, 'consid': 67, 'human': 68, 'everyth': 69, 'go': 70, 'work': 71, 'vote': 72, 'matter': 73, 'peopl

In [81]:
# Training Accuracy

file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/pos/"
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/neg/"
y_act = np.zeros(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos)))
y_act[0:len(os.listdir(file_location_pos))] = 1
y_pred = np.zeros_like(y_act)

iter = 0

pos_x = stem_split(file_location_pos)
for review in pos_x:
    y_pred[iter] = judge(review,phi,phi_y,stemmed_vocab)
    iter += 1

neg_x = stem_split(file_location_neg)
for review in neg_x:
    y_pred[iter] = judge(review,phi,phi_y,stemmed_vocab)
    iter += 1
cmat_train = confusion_matrix(y_pred,y_act)
print(cmat_train)
print(f"Accuracy : {(cmat_train[0,0]+cmat_train[1,1])/np.sum(cmat_train)}")

# Test Accuracy

file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/test/pos/"
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/test/neg/"
y_act = np.zeros(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos)))
y_act[0:len(os.listdir(file_location_pos))] = 1
y_pred = np.zeros_like(y_act)

iter = 0

pos_x = stem_split(file_location_pos)
for review in pos_x:
    y_pred[iter] = judge(review,phi,phi_y,stemmed_vocab)
    iter += 1

neg_x = stem_split(file_location_neg)
for review in neg_x:
    y_pred[iter] = judge(review,phi,phi_y,stemmed_vocab)
    iter += 1
cmat_test = confusion_matrix(y_pred,y_act)
print(cmat_test)
print(f"Accuracy : {(cmat_test[0,0]+cmat_test[1,1])/np.sum(cmat_test)}")

[[11357.   939.]
 [ 1143. 11561.]]
Accuracy : 0.91672
[[8031.  699.]
 [1969. 4301.]]
Accuracy : 0.8221333333333334


## Stemming + Bigrams

In [76]:
bigram_vocab = defaultdict(int)
file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/pos/"
pos_x = bigram_split(file_location_pos,bigram_vocab)
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/neg/"
neg_x = bigram_split(file_location_neg,bigram_vocab)

phi_pos = train_naive_bayes(pos_x,bigram_vocab)
phi_neg = train_naive_bayes(neg_x,bigram_vocab)
phi = [phi_neg,phi_pos]

In [77]:
# Training Accuracy

file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/pos/"
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/neg/"
y_act = np.zeros(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos)))
y_act[0:len(os.listdir(file_location_pos))] = 1
y_pred = np.zeros_like(y_act)

iter = 0

pos_x = bigram_split(file_location_pos)
for review in pos_x:
    y_pred[iter] = judge(review,phi,phi_y,bigram_vocab)
    iter += 1

neg_x = bigram_split(file_location_neg)
for review in neg_x:
    y_pred[iter] = judge(review,phi,phi_y,bigram_vocab)
    iter += 1
cmat_train = confusion_matrix(y_pred,y_act)
print(cmat_train)
print(f"Accuracy : {(cmat_train[0,0]+cmat_train[1,1])/np.sum(cmat_train)}")

# Test Accuracy

file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/test/pos/"
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/test/neg/"
y_act = np.zeros(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos)))
y_act[0:len(os.listdir(file_location_pos))] = 1
y_pred = np.zeros_like(y_act)

iter = 0

pos_x = bigram_split(file_location_pos)
for review in pos_x:
    y_pred[iter] = judge(review,phi,phi_y,bigram_vocab)
    iter += 1

neg_x = bigram_split(file_location_neg)
for review in neg_x:
    y_pred[iter] = judge(review,phi,phi_y,bigram_vocab)
    iter += 1
cmat_test = confusion_matrix(y_pred,y_act)
print(cmat_test)
print(f"Accuracy : {(cmat_test[0,0]+cmat_test[1,1])/np.sum(cmat_test)}")

[[1.2484e+04 3.0000e+00]
 [1.6000e+01 1.2497e+04]]
Accuracy : 0.99924
[[8050.  504.]
 [1950. 4496.]]
Accuracy : 0.8364


## Trigrams + Stemming

In [78]:
trigram_vocab = defaultdict(int)
file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/pos/"
pos_x = trigram_split(file_location_pos,trigram_vocab)
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/neg/"
neg_x = trigram_split(file_location_neg,trigram_vocab)

phi_pos = train_naive_bayes(pos_x,trigram_vocab)
phi_neg = train_naive_bayes(neg_x,trigram_vocab)
phi = [phi_neg,phi_pos]

In [79]:
# Training Accuracy

file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/pos/"
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/train/neg/"
y_act = np.zeros(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos)))
y_act[0:len(os.listdir(file_location_pos))] = 1
y_pred = np.zeros_like(y_act)

iter = 0

pos_x = trigram_split(file_location_pos)
for review in pos_x:
    y_pred[iter] = judge(review,phi,phi_y,trigram_vocab)
    iter += 1

neg_x = trigram_split(file_location_neg)
for review in neg_x:
    y_pred[iter] = judge(review,phi,phi_y,trigram_vocab)
    iter += 1
cmat_train = confusion_matrix(y_pred,y_act)
print(cmat_train)
print(f"Accuracy : {(cmat_train[0,0]+cmat_train[1,1])/np.sum(cmat_train)}")

# Test Accuracy

file_location_pos = "D:/GitHub/COL774/Assignment 2/data/part1_data/test/pos/"
file_location_neg = "D:/GitHub/COL774/Assignment 2/data/part1_data/test/neg/"
y_act = np.zeros(len(os.listdir(file_location_neg))+len(os.listdir(file_location_pos)))
y_act[0:len(os.listdir(file_location_pos))] = 1
y_pred = np.zeros_like(y_act)

iter = 0

pos_x = trigram_split(file_location_pos)
for review in pos_x:
    y_pred[iter] = judge(review,phi,phi_y,trigram_vocab)
    iter += 1

neg_x = trigram_split(file_location_neg)
for review in neg_x:
    y_pred[iter] = judge(review,phi,phi_y,trigram_vocab)
    iter += 1
cmat_test = confusion_matrix(y_pred,y_act)
print(cmat_test)
print(f"Accuracy : {(cmat_test[0,0]+cmat_test[1,1])/np.sum(cmat_test)}")

[[12500.     0.]
 [    0. 12500.]]
Accuracy : 1.0
[[7092. 1022.]
 [2908. 3978.]]
Accuracy : 0.738
